/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSinaisRouteImport } from './routes/_authenticated/sinais'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustosRouteImport } from './routes/_authenticated/custos'
import { Route as AuthenticatedAlertasRouteImport } from './routes/_authenticated/alertas'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSinaisRoute = AuthenticatedSinaisRouteImport.update({
  id: '/sinais',
  path: '/sinais',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustosRoute = AuthenticatedCustosRouteImport.update({
  id: '/custos',
  path: '/custos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlertasRoute = AuthenticatedAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/alertas': typeof AuthenticatedAlertasRoute
  '/custos': typeof AuthenticatedCustosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/sinais': typeof AuthenticatedSinaisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/alertas': typeof AuthenticatedAlertasRoute
  '/custos': typeof AuthenticatedCustosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/sinais': typeof AuthenticatedSinaisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/alertas': typeof AuthenticatedAlertasRoute
  '/_authenticated/custos': typeof AuthenticatedCustosRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/sinais': typeof AuthenticatedSinaisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/alertas'
    | '/custos'
    | '/dashboard'
    | '/relatorios'
    | '/sinais'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/alertas'
    | '/custos'
    | '/dashboard'
    | '/relatorios'
    | '/sinais'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/alertas'
    | '/_authenticated/custos'
    | '/_authenticated/dashboard'
    | '/_authenticated/relatorios'
    | '/_authenticated/sinais'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sinais': {
      id: '/_authenticated/sinais'
      path: '/sinais'
      fullPath: '/sinais'
      preLoaderRoute: typeof AuthenticatedSinaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/custos': {
      id: '/_authenticated/custos'
      path: '/custos'
      fullPath: '/custos'
      preLoaderRoute: typeof AuthenticatedCustosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alertas': {
      id: '/_authenticated/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AuthenticatedAlertasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAlertasRoute: typeof AuthenticatedAlertasRoute
  AuthenticatedCustosRoute: typeof AuthenticatedCustosRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedSinaisRoute: typeof AuthenticatedSinaisRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAlertasRoute: AuthenticatedAlertasRoute,
  AuthenticatedCustosRoute: AuthenticatedCustosRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedSinaisRoute: AuthenticatedSinaisRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
